# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef5b2b4db8f080de813bc8b75333c54ec409372ba946fa8e325ea86cf3a3dbbf615054702124c8b43de2238593214dba38efaef26973178fddbe5528766fc84

test:
  secret_key_base: db63e1f079193d63eb398881f6c3ea07a267bcacb9ace6eaadf93e2654aab852444148d7165b422386ecd66b869daff92acbde08a9b846061974716d4e864021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
